### ISSUE TITLE
Remove Compat?

### ISSUE THREAD

**Issue by samoconnor** [samoconnor/XMLDict.jl#12]
@ararslan I assume the dependancy on Compat introduced by #11 is no longer needed now that 0.6 support is dropped?

**Comment by ararslan** [comment]
Correct, it should be unnecessary. I included it in #11 to maintain support for Julia 0.6.

**Comment by samoconnor** [comment]
Yep. See also comment here https://github.com/samoconnor/Retry.jl/pull/6#issuecomment-406435675
