### ISSUE TITLE
Tag XMLDict 0.3

### ISSUE THREAD

**Issue by omus** [samoconnor/XMLDict.jl#14]
It would be nice to get the version working with Julia 1.0 out. Could you tag XMLDict 0.3 as required by: https://github.com/JuliaLang/METADATA.jl/pull/17086?

**Comment by samoconnor** [comment]
https://github.com/samoconnor/XMLDict.jl/releases/tag/v0.3.0

https://github.com/JuliaLang/METADATA.jl/pull/17513

**Comment by omus** [comment]
Thank you!
