### ISSUE TITLE
XMLError: internal error: Huge input lookup from XML parser

### ISSUE THREAD

**Issue by KwatME** [samoconnor/XMLDict.jl#25]
What's going on?

**Comment by mattBrzezinski** [comment]
Do you have an example of what is broken? What version you are using of the package and Julia?

**Comment by KwatME** [comment]
1.7.2

http://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/7.5.1/msigdb_v7.5.1.xml

Thank you very much.

**Comment by mattBrzezinski** [comment]
> 1.7.2
> 
> http://www.gsea-msigdb.org/gsea/msigdb/download_file.jsp?filePath=/msigdb/release/7.5.1/msigdb_v7.5.1.xml
> 
> Thank you very much.

This is not a public file. Can you post what the error is that you're getting in Julia?

**Comment by KwatME** [comment]
Could you please try downloading the only `.xml` listed here? http://www.gsea-msigdb.org/gsea/downloads.jsp

You can use "kwatme8 at gmail. com"

**Comment by KwatME** [comment]
<img width="759" alt="Screen Shot 2022-02-17 at 13 27 20" src="https://user-images.githubusercontent.com/7741548/154565165-b17b1a1d-7550-4354-84a6-d38623a641de.png">

**Comment by mattBrzezinski** [comment]
This is a problem stemming in [EzXML.jl](https://github.com/JuliaIO/EzXML.jl), most likely because the file is too large and needs to be partitioned down.

**Comment by KwatME** [comment]
Is there anyway to read this big xml?

**Comment by mattBrzezinski** [comment]
Here's a list of [other XML packages](https://juliapackages.com/c/xml) in Julia.

**Comment by KwatME** [comment]
Thank you for looking into this.
